name: Trigger auto deployment for dockerinazure-app-yml

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dockerinazure-app-yml-AutoDeployTrigger-e2de0d3d-211d-4d08-91ba-2eac8acb943d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.DOCKERINAZUREAPPYML_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.DOCKERINAZUREAPPYML_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.DOCKERINAZUREAPPYML_AZURE_SUBSCRIPTION_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: wallism
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: registry.hub.docker.com/wallism/sdlr-capp-dockerinazure-app-yml
          registryUsername: wallism
          registryPassword: ${{ secrets.DOCKERHUB_TOKEN }}
          containerAppName: dockerinazure-app-yml
          imageToBuild: dockerfile:${{ github.sha }}
          resourceGroup: CourseTempOneRG
          _buildArgumentsKey_: |
            _buildArgumentsValues_


