name: Trigger auto deployment for dockerinazure-capp-08-2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dockerinazure-capp-08-2-AutoDeployTrigger-4c7274d3-211a-48d1-828a-79b0c5ebaacb.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DOCKERINAZURECAPP082_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: sprintdeploylearnrepeatcr1.azurecr.io
          registryUsername: ${{ secrets.DOCKERINAZURECAPP082_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOCKERINAZURECAPP082_REGISTRY_PASSWORD }}
          containerAppName: dockerinazure-capp-08-2
          resourceGroup: CourseTempOneRG
          imageToBuild: sprintdeploylearnrepeatcr1.azurecr.io/dockerinazure-capp-08-2:${{ github.sha }}
          
            

     

