name: Trigger auto deployment for dockerinazure-capp-07

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/dockerinazure-capp-07-AutoDeployTrigger-b59df604-7750-4d28-b553-ba68a8d1953e.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DOCKERINAZURECAPP07_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/src
          registryUrl: sprintdeploylearnrepeatcr1.azurecr.io
          registryUsername: ${{ secrets.DOCKERINAZURECAPP07_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.DOCKERINAZURECAPP07_REGISTRY_PASSWORD }}
          containerAppName: dockerinazure-capp-07
          resourceGroup: CourseTempOneRG
          imageToBuild: sprintdeploylearnrepeatcr1.azurecr.io/dockerinazure-capp-07:${{ github.sha }}
          dockerfilePath: DockerInAzure/Dockerfile
            

     

